setup a local mocking api with fastapi
Jaydee94/kubeseal-webgui pull request #149
Opened 2022-10-01 18:12 UTC by Jaydee94

can be used for local development

2022-10-01 18:16 UTC, Jaydee94 commented on mock/kswg_mock/routers/kubeseal.py
> +        exec_kubeseal_command,
intended

2022-10-02 18:08 UTC, FSchumacher requested changes

2022-10-02 18:08 UTC, FSchumacher commented on mock/kswg_mock/routers/kubeseal.py
> +    os.remove(temp_secret_file)
Will not work, when `type == "text"`.

2022-10-05 17:26 UTC, FSchumacher approved these changes

2022-10-05 17:57 UTC, merged